language: python
python:
  - 3.3
  - 3.4
env:
  - NSQ_DOWNLOAD=nsq-0.2.24.linux-amd64.go1.2 TORNADO_VERSION=2.4.1
  - NSQ_DOWNLOAD=nsq-0.2.24.linux-amd64.go1.2 TORNADO_VERSION=3.0.2
  - NSQ_DOWNLOAD=nsq-0.2.24.linux-amd64.go1.2 TORNADO_VERSION=3.1.1
  - NSQ_DOWNLOAD=nsq-0.2.24.linux-amd64.go1.2 TORNADO_VERSION=3.2
  - NSQ_DOWNLOAD=nsq-0.2.27.linux-amd64.go1.2 TORNADO_VERSION=2.4.1
  - NSQ_DOWNLOAD=nsq-0.2.27.linux-amd64.go1.2 TORNADO_VERSION=3.0.2
  - NSQ_DOWNLOAD=nsq-0.2.27.linux-amd64.go1.2 TORNADO_VERSION=3.1.1
  - NSQ_DOWNLOAD=nsq-0.2.27.linux-amd64.go1.2 TORNADO_VERSION=3.2
  - NSQ_DOWNLOAD=nsq-0.2.28.linux-amd64.go1.2.1 TORNADO_VERSION=2.4.1
  - NSQ_DOWNLOAD=nsq-0.2.28.linux-amd64.go1.2.1 TORNADO_VERSION=3.0.2
  - NSQ_DOWNLOAD=nsq-0.2.28.linux-amd64.go1.2.1 TORNADO_VERSION=3.1.1
  - NSQ_DOWNLOAD=nsq-0.2.28.linux-amd64.go1.2.1 TORNADO_VERSION=3.2
install:
  - pip install simplejson
  - export PYCURL_SSL_LIBRARY=openssl
  - pip install pycurl
  - pip install six
  - pip install tornado==$TORNADO_VERSION
  - sudo apt-get install libsnappy-dev
  - pip install python-snappy
  - wget http://bitly-downloads.s3.amazonaws.com/nsq/$NSQ_DOWNLOAD.tar.gz
  - tar zxvf $NSQ_DOWNLOAD.tar.gz
  - sudo cp $NSQ_DOWNLOAD/bin/nsqd $NSQ_DOWNLOAD/bin/nsqlookupd /usr/local/bin
script: py.test
notifications:
  email: false
